# Usa PHP-FPM en Alpine (ligero y rápido) // ssh -i c:\Users\serve\Desktop\TFG\AWS\RODAE_backend_keys.pem  ubuntu@ec2-34-247-163-27.eu-west-1.compute.amazonaws.com
FROM php:8.3-fpm-alpine

# Paquetes del sistema y extensiones necesarias
RUN apk add --no-cache \
    bash curl git unzip icu-dev oniguruma-dev libzip-dev \
    mariadb-client \
 && docker-php-ext-install pdo_mysql bcmath exif intl zip pcntl

# Opcional: GD (si algún día procesas imágenes en el back)
# RUN apk add --no-cache libpng-dev libjpeg-turbo-dev freetype-dev
# RUN docker-php-ext-configure gd --with-freetype --with-jpeg
# RUN docker-php-ext-install gd

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && rm composer-setup.php

WORKDIR /var/www/html

# Copiamos el código
# (En compose montaremos el proyecto como volumen, pero esto
#  permite construir imágenes deployables si lo prefieres)
COPY . /var/www/html

# Asegurar permisos de carpetas de cache/storage
RUN chown -R www-data:www-data storage bootstrap/cache \
 && chmod -R 775 storage bootstrap/cache

# Entrypoint: crea overrides de php.ini, espera la DB, instala deps,
# cachea config/rutas, ejecuta migraciones y lanza php-fpm
COPY ./entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Arranca PHP-FPM con el entrypoint
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["php-fpm", "-F"]
