server {
  listen 80;
  server_name _;
  root /var/www/html/public;
  index index.php;

  # Laravel: servir estáticos si existen, si no pasar a index.php
  location / {
    try_files $uri $uri/ /index.php?$query_string;
  }

  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_pass app:9000;
    fastcgi_read_timeout 300;
  }

  # Mejor manejo de uploads grandes
  client_max_body_size 256m;
  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 65;
}
